services:
  postgres:
    image: postgres:15.3
    container_name: nestjs-postgres
    env_file:
      - docker.env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4:7.5
    container_name: nestjs-pgadmin
    ports:
      - '5050:80'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - postgres
    env_file:
      - docker.env

networks:
  postgres:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
